/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)

    // Source: https://mvnrepository.com/artifact/org.openjfx/javafx-fxml
    implementation("org.openjfx:javafx-fxml:21.0.12")
    // Source: https://mvnrepository.com/artifact/org.openjfx/javafx-controls
    implementation("org.openjfx:javafx-controls:21.0.12")

    implementation("io.github.mkpaz:atlantafx-base:2.0.0")

    // Source: https://mvnrepository.com/artifact/org.kordamp.ikonli/ikonli-core
    implementation("org.kordamp.ikonli:ikonli-core:12.4.0")

    // Source: https://mvnrepository.com/artifact/org.kordamp.ikonli/ikonli-javafx
    implementation("org.kordamp.ikonli:ikonli-javafx:12.4.0")

    // Source: https://mvnrepository.com/artifact/org.kordamp.ikonli/ikonli-fontawesome5-pack
    implementation("org.kordamp.ikonli:ikonli-fontawesome5-pack:12.4.0")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// tells the javafx plugin which modules to add to the runtime.
javafx {
    version = "21.0.12"
    modules = listOf("javafx.controls", "javafx.fxml")
}

application {
    // Define the main class for the application.
    mainClass = "e.dream.Launcher"
}
